# Site settings
title: photo-stitcher
baseurl: ""
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  style: compressed
  sass_dir: _scss

gems:
  # - jekyll-coffeescript


